package $Actuatordriver.factoryPackageName$;

import $Actuatordriver.PackageName$.*;

public class  $Actuatordriver.name$Factory  { 
   
   public static I$Actuatordriver.name$ get$Actuatordriver.name$(String name$Actuatordriver.name$) {
  
       // if (name$Actuatordriver.name$.equals("Android"))
        //  return new Android$Actuatordriver.name$();  // Register  device specific driver
        
       // if (name$Actuatordriver.name$.equals("iOS"))
          // return new IOS$Actuatordriver.name$();     
    
    return null;       
}

}