package $GUIdriver.factoryPackageName$;

//import $GUIdriver.PackageName$.*;

public class  $GUIdriver.name$Factory  { 
   
   //public static I$GUIdriver.name$ get$GUIdriver.name$(String name$GUIdriver.name$) {
  
       // if (name$Actuatordriver.name$.equals("Android"))
        //  return new Android$Actuatordriver.name$();  // Register  device specific driver
        
       // if (name$Actuatordriver.name$.equals("iOS"))
          // return new IOS$Actuatordriver.name$();     
    
    //return null;       
//}

}