package $Actuatordriver.factoryDeviceImplActuator$;

import framework.*;

/* Rename class-name with Implementation.   */

public class Impl$Actuatordriver.name$ implements I$Actuatordriver.name$ {

  $Actuatordriver.allActions:{ action |   
  @Override
  public void $action.name$($action.allParameter:{ param | $param.type.name$ arg }; 
   separator=", "$) {
   
   } 
    
   }; separator="\n"$ 
 
}


