package $Actuatordriver.logicPackageName$;

import fr.inria.arles.pankesh.pubsubmiddleware.PubSubMiddleware;
import fr.inria.arles.pankesh.semanticmodel.*;
import $Actuatordriver.PackageName$.*;
  
   
public  class  Fake$Actuatordriver.name$ extends $Actuatordriver.name$  {	

	public Fake$Actuatordriver.name$(PubSubMiddleware myPubSubMiddleware, Device deviceInfo) {
		super(myPubSubMiddleware, deviceInfo);

	}	
	
    $Actuatordriver.allActions:{ action |     
    @Override
    protected  void $action.name$($action.allParameter:{ param | $param.type.name$ arg }; separator=", "$) {
      //TODO : write code here
    
    }
    
    }; separator="\n"$
	
}
   
     
    
