package $SensorDriver.logicPackageName$;

import fr.inria.arles.pankesh.pubsubmiddleware.PubSubMiddleware;
import fr.inria.arles.pankesh.semanticmodel.*;
import $SensorDriver.PackageName$.*;

public class  Fake$SensorDriver.name$ extends $SensorDriver.name$  { 
   
	public Fake$SensorDriver.name$(PubSubMiddleware pubSubM, Device deviceInfo) {
		super(pubSubM, deviceInfo);

	}	
	
	$SensorDriver.allGeneratedInfo:{ generatedInfo | 	
	
	@Override
	public void handle$generatedInfo.name; format="capital"$()	{
	     // TODO : write code Here
	}
   
}; separator="\n"$
		
		@Override
		protected void handleExpiryOfTimer() {
			//TODO: For periodic sensing : it is  for 10 seconds	
			
		}	
	
}
	
	
	
	
	


    
	
	
    

    