package $Storageservice.logicPackageName$;

import fr.inria.arles.pankesh.pubsubmiddleware.PubSubMiddleware;
import fr.inria.arles.pankesh.semanticmodel.*;
import $Storageservice.PackageName$.*;



public class  Fake$Storageservice.name$  extends $Storageservice.name$  {
	
	public Fake$Storageservice.name$(PubSubMiddleware pubSubM, Device deviceInfo) {
		super(pubSubM, deviceInfo);

	}

}


  

        
    
	
	
    

    