package $Storageservice.logicPackageName$;

import fr.inria.arles.pankesh.pubsubmiddleware.PubSubMiddleware;
import fr.inria.arles.pankesh.semanticmodel.*;
import $Storageservice.PackageName$.*;



public class  Fake$Storageservice.name$  extends $Storageservice.name$  {
	
	public Fake$Storageservice.name$(PubSubMiddleware pubSubM, Device deviceInfo, Object ui) {
		super(pubSubM, deviceInfo);

	}
	
	$Storageservice.allDataAccess:{ dataAccess |
	
	@Override
	public void onNew$dataAccess.dataAccessName; format="capital"$RequestReceived( String arg) {
		//TODO : write code here

	}
	
	}$

}


  

        
    
	
	
    

    