package fr.inria.arles.pankesh.gen.logic;

import fr.inria.arles.pankesh.pubsubmiddleware.PubSubMiddleware;
import fr.inria.arles.pankesh.semanticmodel.*;
import fr.inria.arles.pankesh.gen.$Storageservice.name$;



public class  Fake$Storageservice.name$  extends $Storageservice.name$  {
	
	public Fake$Storageservice.name$(PubSubMiddleware pubSubM, Device deviceInfo) {
		super(pubSubM, deviceInfo);

	}

}


  

        
    
	
	
    

    