package $SensorDriver.factoryPackageName$;

import $SensorDriver.PackageName$.*;

public class  $SensorDriver.name$Factory  { 
   
   public static I$SensorDriver.name$ get$SensorDriver.name$(String name$SensorDriver.name$) {
  
       // if (name$SensorDriver.name$.equals("Android"))
        //  return new Android$SensorDriver.name$();  // Register  device specific driver
        
       // if (name$SensorDriver.name$.equals("iOS"))
          // return new IOS$SensorDriver.name$();     
    
    return null;       
}

}