package $Storageservice.factoryPackageName$;

import $Storageservice.packageName$.*;



public class  $Storageservice.name$Factory  { 
   
   public static I$Storageservice.name$ get$Storageservice.name$(String name$Storageservice.name$) {
  
       // if (name$Storageservice.name$.equals("mysql"))
        //  return new AndroidBadgeReader();  // Register  device specific driver
        
       // if (name$Storageservice.name$.equals("mongodb"))
          // return new IOSBadgeReader();     
    
    return null;       
}

}     